-- ============================================================
-- Integrante 2 — pruebas de ubicación en tiempo real
-- ============================================================
-- Este archivo se conserva para documentar el orden de inicialización, pero
-- ya no modifica horarios ni crea inscripciones persistentes.
--
-- La versión anterior convertía la sección PRG1 de Juan en una clase de
-- 00:00 a 23:59. Ese rango no corresponde a un bloque oficial USACH y hacía
-- que PRG1 apareciera en la leyenda, pero no dentro de la grilla de horarios.
--
-- Los casos dependientes de CURRENT_TIME se crean ahora como fixtures
-- temporales durante las pruebas de integración y se eliminan junto con la
-- base de datos desechable. El seed de demostración permanece determinista.
