# puerto donde corre el backend
server.port=${BACKEND_HOST_PORT:9090}
# configuracion de conexion a PostgreSQL con variables de entorno
spring.datasource.url=jdbc:postgresql://${BD_HOST:localhost}:${DB_HOST_PORT:5432}/academic_db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=-1
# configuracion de MongoDB con driver oficial (sin Spring Data MongoDB)
app.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/?directConnection=true&serverSelectionTimeoutMS=5000}
app.mongodb.database=${MONGO_DATABASE:academic_mongo}
# swagger ui
springdoc.swagger-ui.path=/swagger-ui/index.html
