# puerto donde corre el backend
server.port=8081

# configuracion de conexion a PostgreSQL con variables de entorno
spring.datasource.url=jdbc:postgresql://${BD_HOST:localhost}:${DB_HOST_PORT:5432}/academic_db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

# swagger ui
springdoc.swagger-ui.path=/swagger-ui/index.html
