# puerto donde corre el backend
server.port=${BACKEND_HOST_PORT:9090}

# configuracion de conexion a PostgreSQL con variables de entorno
spring.datasource.url=jdbc:postgresql://${BD_HOST:localhost}:${DB_HOST_PORT:5432}/academic_db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

# swagger ui
springdoc.swagger-ui.path=/swagger-ui/index.html


spring.sql.init.mode=always
spring.sql.init.schema-locations=file:database/1_db_schema.sql,file:database/2_db_mock.sql,file:database/3_i2_accessibility.sql,file:database/4_i2_test_active_section.sql
spring.sql.init.continue-on-error=true
spring.sql.init.separator=;