# puerto donde corre el backend
server.port=8080

# configuracion de conexion a PostgreSQL con variables de entorno
spring.datasource.url=jdbc:postgresql://${BD_HOST:localhost}:5432/academic_db
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# swagger ui
springdoc.swagger-ui.path=/swagger-ui/index.html